[project]
name = "vid-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deno>=2.5.4",
    "hurry-filesize>=0.9",
    "keyring>=25.6.0",
    "pyqt6>=6.9.1",
    "requests>=2.32.5",
    "wakepy>=0.10.2.post1",
    "yt-dlp>=2025.7.21",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "T201",   # `print` found: Prevents print statements (prefers proper logging).
    "D103",   # Missing docstring in public function: Requires comments for all functions.
    "D212",   # Multi-line docstring summary should start at the first line.
    "D413",   # Missing blank line after last section in docstring.
    "E501",   # Line too long: Enforces the standard 88 or 120 character limit.
    "ERA001", # Found commented-out code: Prevents "dead code" from cluttering files.
    "TD002",  # Missing author in TODO: Requires `TODO(name):` format.
    "TD003",  # Missing issue link on the line following a TODO.
    "FIX002", # Line contains TODO
]
