"""
Guards against Settings -> About's version drifting from pyproject.toml again.

APP_VERSION (src/version_utils.py) is read from installed package metadata
(importlib.metadata), which only reflects pyproject.toml after an editable
install refreshes it. These tests pin the two places that must stay in sync
so a future edit can't silently drop the refresh step or re-track the
generated metadata directory.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_GIT = shutil.which("git")
_RELEASE_SCRIPT = _REPO_ROOT / "scripts" / "release.ps1"


def test_release_script_refreshes_editable_install_metadata() -> None:
    # release.ps1 is gitignored (scripts/* -- it's a personal convenience script,
    # never committed), so it won't exist on a fresh clone or CI runner.
    if not _RELEASE_SCRIPT.exists():
        pytest.skip("scripts/release.ps1 is a local, gitignored file")
    content = _RELEASE_SCRIPT.read_text(encoding="utf-8")
    version_stamp_index = content.index("uv version $Version")
    install_index = content.index("uv pip install -e .")
    assert install_index > version_stamp_index, (
        "release.ps1 must run `uv pip install -e .` after stamping the version, "
        "so importlib.metadata.version('meadowlark') picks up the new version "
        "(mirrors the 'Install package in editable mode' step in "
        ".github/workflows/release.yml)."
    )


def test_egg_info_is_gitignored_and_not_tracked() -> None:
    gitignore = (_REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
    assert "*.egg-info/" in gitignore, (
        "*.egg-info/ must stay gitignored -- a committed copy freezes "
        "Settings -> About's version at whatever it read when committed."
    )
    assert _GIT is not None, "git must be on PATH to run this test"
    tracked = subprocess.run(  # noqa: S603 -- fixed argv, no shell, trusted git binary
        [_GIT, "ls-files", "meadowlark.egg-info"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    assert tracked == "", (
        "meadowlark.egg-info must not be committed -- it is regenerated by "
        "`uv pip install -e .` and a stale committed copy overrides the real "
        "version whenever this repo is on sys.path (see release.ps1)."
    )
